/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package my.kotlin.app.app

class MessageUtils {
    companion object {
        fun getMessage(): String = "Hello      World! I'm Kotlin!"
    }
}
